'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const profile = require('../src/document-profile');

const source = `---\nid: project:demo\ndocumentProfile:\n  schemaVersion: 1\n  name: service\n  traits: [api, operations]\n  policy:\n    required: [PRD, REQ, API, RUN]\n    recommended: [ARC, MOD, TST]\n    onDemand: [SCR, ADR, GLS]\n    disabled: []\n---\n# Demo\n`;
const parsed = profile.parseDocumentProfile(source);
assert.strictEqual(parsed.name, 'service');
assert.deepStrictEqual(parsed.policy.required, ['PRD', 'REQ', 'API', 'RUN']);
assert.strictEqual(new Set(Object.values(parsed.policy).flat()).size, 10);
assert(profile.PROFILE_NAMES.every((name) => profile.normalizeProfile({ name }).policy));
const emptyRequired = profile.normalizeProfile({ name: 'service', policy: { required: [], recommended: [], onDemand: profile.REGULAR_TYPES, disabled: [] } });
assert.deepStrictEqual(emptyRequired.policy.required, []);
assert.deepStrictEqual(emptyRequired.policy.recommended, []);
assert.throws(() => profile.renderDocumentProfile({ name: 'service', policy: { required: ['PRD', 'PRD'], recommended: [], onDemand: [], disabled: [] } }), /중복/u);
assert.throws(() => profile.renderDocumentProfile({ name: 'unknown' }), /지원하지 않는/u);
const invalidProfile = source.replace('traits: [api, operations]', 'traits: [api, bogus]').replace('name: service', 'revision: abc\n  name: service\n  history: [service, bogus]');
const invalidValidation = profile.validateDocumentProfile(invalidProfile);
assert(invalidValidation.errors.some((message) => message.includes('bogus')));
assert(invalidValidation.errors.some((message) => message.includes('revision')));

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'rundol-profile-'));
const file = path.join(temp, 'project.md');
fs.writeFileSync(file, source, 'utf8');
profile.applyToProject(file, { name: 'lean', traits: ['api'] });
const updated = fs.readFileSync(file, 'utf8');
assert.strictEqual(profile.parseDocumentProfile(updated).name, 'lean');
assert(updated.includes('documentProfile:'));
profile.reconfigureProject(file, 'platform');
const reconfigured = profile.parseDocumentProfile(fs.readFileSync(file, 'utf8'));
assert.strictEqual(reconfigured.name, 'platform');
assert.deepStrictEqual(reconfigured.traits, ['api']);
assert.strictEqual(reconfigured.revision, 2);
assert.deepStrictEqual(reconfigured.history, ['lean', 'platform']);
const canonicalA = profile.normalizeProfile({ name: 'lean', traits: ['operations', 'ui'] });
const canonicalB = profile.normalizeProfile({ name: 'lean', traits: ['ui', 'operations'] });
assert.deepStrictEqual(canonicalA, canonicalB);
const overrideA = profile.normalizeProfile({ name: 'lean', policy: { required: ['REQ', 'PRD'], recommended: ['TST', 'ARC'], onDemand: ['GLS', 'RUN', 'API', 'ADR', 'MOD', 'SCR'], disabled: [] } });
const overrideB = profile.normalizeProfile({ name: 'lean', policy: { required: ['PRD', 'REQ'], recommended: ['ARC', 'TST'], onDemand: ['SCR', 'MOD', 'API', 'ADR', 'RUN', 'GLS'], disabled: [] } });
assert.deepStrictEqual(overrideA, overrideB);
assert(profile.missingActions(canonicalA, ['PRD']).some((item) => item.type === 'REQ' && item.command.includes('rdl doc create REQ')));
assert(profile.missingActions(canonicalA, ['PRD']).find((item) => item.type === 'REQ').command.includes('--related <ARTIFACT-ID>'));
const legacyFile = path.join(temp, 'legacy-project.md');
fs.writeFileSync(legacyFile, '---\nid: project:legacy\ntype: project\n---\n# Legacy\n', 'utf8');
const legacyConfigured = profile.reconfigureProject(legacyFile, 'lean');
assert.strictEqual(legacyConfigured.legacyUnconfigured, true);
assert.strictEqual(legacyConfigured.profile.revision, 1);
fs.rmSync(temp, { recursive: true, force: true });
process.stdout.write('document profile tests passed\n');
